version: 0.0
os: linux
files:
  - source: /.
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: 
    - location: scripts/start_server.sh
      timeout: 300
      runas: 
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: 

